### ISSUE TITLE
Could not resolve org.eclipse.edc:edc-build:0.0.1-SNAPSHOT

### ISSUE THREAD

**Issue by rizwanmehmood94** [eclipse-edc/Samples#55]
# Bug Report

## Describe the Bug
_A clear and concise description of the bug._

### Expected Behavior
_A clear and concise description of what you expected to happen._

### Observed Behavior
_A clear and concise description of what happened instead._

## Context Information
_Add any other context about the problem here._

- Used version [e.g. EDC v1.0.0]
- OS: [e.g. iOS, Windows]recent:///df1e6a5f19112f69b
![Screenshot from 2023-05-23 12-45-59](https://github.com/eclipse-edc/Samples/assets/51752121/81225114-3339-4df2-adf6-c170b3ec2a7c)
589962d646c99ec

- ...

## Detailed Description
_If applicable, add screenshots and logs to help explain your problem._

## Possible Implementation
_You already know the root cause of the erroneous state and how to fix it? Feel free to share your thoughts._

**Comment by wolf4ood** [comment]
Hi @rizwanmehmood94  thanks for raising this, 
that's because we are rolling out the upgrade to Java 17 to EDC and all related libraries outline in this [DR](https://github.com/eclipse-edc/Connector/pull/3055)

This is the [PR](https://github.com/eclipse-edc/Connector/pull/3070) on EDC.

It will be fixed once the upgrade is completed in all project libraries

Thanks

**Comment by ndr-brt** [comment]
@rizwanmehmood94 I'd add that it will be impossible to build the EDC with Java 11, please upgrade to Java 17
