### ISSUE TITLE
Transfer Sample 04 terminating immediately after startup

### ISSUE THREAD

**Issue by eschrewe** [eclipse-edc/Samples#86]
# Bug Report

## Describe the Bug
A few seconds after completing the docker-compose, a failing http request in the the provider_1 container causes this container to terminate. 

### Expected Behavior
All containers should stay up and running. 

### Observed Behavior
A few seconds after completing the docker-compose, a failing http request in the the provider_1 container causes this container to terminate. The other containers are then terminating as well (like they should in such as case, since we are using the "--abort-on-container-exit" parameter). 

## Steps to Reproduce
1. Clone the Samples Project from Github.
2. Configure, build and run Sample No. 1 as described in the README. (Everything is working just fine here)
3. Download opentelemetry agent. Copy this file to the Sample04 root folder. (As instructed by the README)
4. Build Sample04 (of course using the given Gradle Wrapper)
5. Run docker-compose as specified in the README. 

## Context Information

Xubuntu 22.04  
Docker version 24.0.4, build 3713ee1
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.10.6
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022
openjdk 17.0.7 2023-04-18
OpenJDK Runtime Environment (build 17.0.7+7-Ubuntu-0ubuntu122.04.2)
OpenJDK 64-Bit Server VM (build 17.0.7+7-Ubuntu-0ubuntu122.04.2, mixed mode, sharing)

## Detailed Description
I have attached the logging output here:  
[log.txt](https://github.com/eclipse-edc/Samples/files/12011317/log.txt)

## Possible Implementation
None that I know of.

**Comment by matthiasdg** [comment]
It's actually the consumer that exits because of `SEVERE : Error booting runtime: The following injected fields were not provided: Field "dataPlaneInstanceStore" of type [interface org.eclipse.edc.connector.dataplane.selector.spi.store.DataPlaneInstanceStore] required by org.eclipse.edc.connector.catalog.CatalogDefaultServicesExtension`.

The provider timeouts/deadlines do not really cause something to terminate.

It seems the sample is not up to date; you can get it working by looking at `transfer-01-file-transfer`:

- There is a `implementation(libs.edc.data.plane.selector.core)` dependency missing in the build.gradle, causing the error above.
- After that, I still got an http error when posting the contract offer, replaced that with the one from sample transfer 01 (here and there you have to replace localhost with provider, similar for filetransfer.json), also replaced docker compose env vars with what's in the `config.properties` of transfer 01 (e.g. EDC_DSP_CALLBACK_ADDRESS instead of IDS_WEBHOOK_ADDRESS; these env vars get translated into config if I look at `ConfigFactory.java`); that seemed to get it working.

**Comment by ndr-brt** [comment]
@matthiasdg would you mind provide a PR to fix the issue?

**Comment by matthiasdg** [comment]
opened PR (can't login in newly created eclipse foundation account and fill out contributor agreement though, sent mail to webmaster)
